### ISSUE TITLE
[Request] Allow to edit CRYOSTAT_K8S_NAMESPACES

### ISSUE THREAD

**Issue by ElfoLiNk** [cryostatio/cryostat-helm#119]
### Describe the feature

Would be good to be able to edit CRYOSTAT_K8S_NAMESPACES to watch multiple namespaces.

Probabily also Role and RoleBinding needs fixes to support that

**Comment by andrewazores** [comment]
Thanks @ElfoLiNk , that's a good idea for a feature. It will probably be a while before we're able to prioritize working on that, but I'd be very happy to review such a PR :-)

**Comment by tthvo** [comment]
This is now possible after #128 :D

**Comment by tthvo** [comment]
This should be now configurable with the latest `main` and 3.0+ ^^
