### ISSUE TITLE
[Request] Upload helm charts to github packages registry

### ISSUE THREAD

**Issue by grzesuav** [cryostatio/cryostat-helm#161]
### Describe the feature

Currently helm chart is published as a release file, this is feature request to push it also to OCI registry associated with github project. It makes it easier to use with i.e. argocd

### Anything other information?

One ammong many guides is https://trstringer.com/helm-charts-github-container-registry/

**Comment by tthvo** [comment]
@grzesuav Released charts are also available at helm repository: https://cryostat.io/helm-charts. Would this help in your case? With argocd, you can specify `RepoURL`, I believe.

**Comment by andrewazores** [comment]
@grzesuav the Helm chart in OCI form is available now: https://github.com/cryostatio/cryostat-helm/pkgs/container/cryostat-helm . Thanks for the suggestion!
