### ISSUE TITLE
[Request] Include semver major number in resource names

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat-helm#200]
This is just another temporary/one-time workaround the same as `--force` IMO, because we would have to do another rename again in the future if we change the labels again or do anything else similar.

Maybe a naming scheme like `{{ include "cryostat.fullname" . }}-v{{ cryostat.semver.major }}`, which would expand out to ex. `cryostat-v3`, could be usable across the various resources. This way their names stay stable within a major release version, but on major version upgrade when things are expected to change in a breaking way anyway, then the resources are renamed and upgrades can be done without force.

_Originally posted by @andrewazores in https://github.com/cryostatio/cryostat-helm/pull/197#discussion_r1772039428_

**Comment by tthvo** [comment]
https://helm.sh/docs/chart_template_guide/function_list/#semver

**Comment by andrewazores** [comment]
Done in #202
