### ISSUE TITLE
kubeVersion does not match with EKS

### ISSUE THREAD

**Issue by ksawerykarwacki** [cryostatio/cryostat-helm#53]
I am using EKS with crossplane helm provider to deploy helm charts. Trying to deploy this chart I got:

`create failed: failed to install release: chart requires kubeVersion: >=1.19.0 which is incompatible with Kubernetes v1.24.8-eks-ffeb93d`

Removing line from Chart.yaml helped to run smoothly.

**Comment by andrewazores** [comment]
https://github.com/helm/helm/issues/10375

Seems like a mismatch between helm's expected versioning scheme and what EKS reports itself as.

Here's an example of how another chart worked around it:

https://github.com/traefik/traefik-helm-chart/issues/698

**Comment by ebaron** [comment]
Hi @ksawerykarwacki, this should be fixed in our upcoming Cryostat 2.3 release. We're aiming to have that released in roughly one month.
